documents: 'src/graphql/documents/*.{gql,graphql}'
schema: http://localhost:8000/api/graphql

extensions:
  codegen:
    overwrite: true
    schema: http://localhost:8000/api/graphql
    documents: 'src/graphql/documents/*.{gql,graphql}'

    generates:
      src/graphql/generated.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-urql"

      src/graphql/query-types-hooks.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-react-query"

    config:
      inputMaybeValue: T | undefined
      declarationKind:
        type: 'interface'
        input: 'interface'
        interface: 'interface'
        arguments: 'interface'
      federation: true
      constEnums: true
      namingConvention:
            typeNames: keep
            enumValues: change-case-all#constantCase


