mutation AddVisitor($uid: String!, $provider: VisitorProvider = Facebook) {
    upsertVisitor(
        upsert: {
            create: {
                uid: $uid,
                provider: $provider,
            },
            update: {
                uid: $uid,
                provider: $provider,
            },
        },
        where: {
            uid: $uid
        }
    ) {
      uid
    }
}