query GetHomePageData {
  info(where: { email: "dev.rayat000@gmail.com" }) {
    name
    email
    phone
    description
    aboutMe {
      raw
    }
    experienceYears
  }
  skills(where: { percent_gte: 70 }) {
    id
    name
    percent
    type
  }
  educations: journeys(where: { type: EDUCATION }) {
    ...MyJourney
  }
  experiences: journeys(where: { type: EXPERIENCE }) {
    ...MyJourney
  }
  projects {
    id
    title
    slug
    description {
      raw
    }
    source
    demo
    images(first: 1) {
      id
      label
      image
    }
  }
  visitors {
    uid
  }
}

query GetMyInfo {
  info(where: { email: "dev.rayat000@gmail.com" }) {
    name
    email
    phone
    description
  }
}

query GetMyExpertise {
  skills(where: { percent_gte: 70 }) {
    id
    name
    percent
    type
  }
}

query GetMyEducation {
  educations: journeys(where: { type: EDUCATION }) {
    ...MyJourney
  }
}

query GetMyExperience {
  experiences: journeys(where: { type: EXPERIENCE }) {
    ...MyJourney
  }
}

query GetProjects {
  projects {
    id
  }
}

query GetProjectBySlug($slug: String!) {
  project(where: { slug: $slug }) {
    title
    description {
      raw
    }
    source
    demo
    images {
      id
      label
      image
    }
  }
}

query GetVisitorCount {
  visitors {
    uid
  }
}
