# Use postgres/example user/password credentials
version: '3.1'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: ppooii12
  #     POSTGRES_DB: 'keeper'
  #   ports:
  #     - 5066:5432
  #   volumes:
  #     - ./db:/var/lib/postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
  #     PGADMIN_DEFAULT_PASSWORD: ppooii12
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db

  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - 6379:6379

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '5051:8081'
    depends_on:
      - redis
