import Head from 'next/head'
import Image from 'next/image'
// import { query } from '.keystone/api'

// import { useGetProjectsQuery, GetProjectsDocument } from '$graphql/generated'
// import { GetServerSideProps } from 'next'
// import { createSSRExchange, createUrqlClient } from '$utils/urql_client'
// import { DocumentRenderer } from '@keystone-6/document-renderer'
// import { getImageUrl } from '$lib/utils/image-url'
import Intro from '$lib/components/home/intro'
import Services from '$lib/components/home/services'
import { ScrollArea } from '@mantine/core'

export default function Home() {
  return (
    <ScrollArea type="scroll" style={{ height: '100vh' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Services />
    </ScrollArea>
  )
}

// export const getServerSideProps: GetServerSideProps = async ctx => {
//   const ssrCache = createSSRExchange()
//   const client = createUrqlClient(ssrCache)

//   await client.query(GetProjectsDocument).toPromise()

//   return {
//     props: {
//       urqlState: ssrCache.extractData(),
//     },
//   }
// }
