import Head from 'next/head'
import Image from 'next/image'
// import { query } from '.keystone/api'

// import { useGetProjectsQuery, GetProjectsDocument } from '$graphql/generated'
// import { GetServerSideProps } from 'next'
// import { createSSRExchange, createUrqlClient } from '$utils/urql_client'
// import { DocumentRenderer } from '@keystone-6/document-renderer'
// import { getImageUrl } from '$lib/utils/image-url'
import Intro from '$lib/components/home/intro'
import Services from '$lib/components/home/services'
import { AppShell, createStyles, Navbar, ScrollArea } from '@mantine/core'
import MyAside from '$lib/components/home/aside'

const useStyles = createStyles(theme => ({
  main: {
    backgroundColor:
      theme.colorScheme == 'light'
        ? theme.colors.gray[1]
        : theme.colors.gray[8],
    paddingTop: 0,
  },
}))

export default function Home() {
  const { classes } = useStyles()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        navbarOffsetBreakpoint="md"
        asideOffsetBreakpoint="md"
        navbar={
          <Navbar width={{ base: 280 }} p="xs">
            hi
          </Navbar>
        }
        aside={<MyAside />}
        classNames={{
          main: classes.main,
        }}
      >
        <ScrollArea type="scroll" style={{ height: '100vh' }}>
          <Intro />
          <Services />
        </ScrollArea>
      </AppShell>
    </div>
  )
}

// export const getServerSideProps: GetServerSideProps = async ctx => {
//   const ssrCache = createSSRExchange()
//   const client = createUrqlClient(ssrCache)

//   await client.query(GetProjectsDocument).toPromise()

//   return {
//     props: {
//       urqlState: ssrCache.extractData(),
//     },
//   }
// }
